### ISSUE TITLE
1.4 As a donor, I want to know the minimal conditiion for a textbook to be donated so that I can donate textbooks that are in good condition

### ISSUE THREAD

**Issue by ChrisSWood** [Djaenk/Textbook-Foundation#12]
Rating: 0

Given a textbook is in bad condition, when the donors upload the textbook's condition online, the website can return the donation because the textbook is in bad condition

**Comment by KirkWThomas** [comment]
@cessanchez1190 put the 'minimal condition' as a static paragraph on the donate screen
