### ISSUE TITLE
3.2 - As a borrower, I want to be able to view important book information on the checkout page

### ISSUE THREAD

**Issue by jheckSMU** [Djaenk/Textbook-Foundation#14]
3

As a borrower
I want to be able to view important book information on the checkout page
So I can easily see important book details on the page

Given a borrower is on the checkout page
When they have a book selected
Then the book's ISBN, name, author, publication date should be shown

**Comment by KirkWThomas** [comment]
checkout page is the same as book page, all relevant information is shown on book page
