### ISSUE TITLE
5.2 I want to see what books are highly requested

### ISSUE THREAD

**Issue by Djaenk** [Djaenk/Textbook-Foundation#15]
I want to see what books are highly requested so that I can take some items off of the waitlist and donate books that are in short supply.

Given a donor is signed in, the user can view a list of all the books currently on the request list along with the number of requests for each book.

Given a donor is viewing the list, the user has the option to sort based on demand, urgency, location, etc.

**Comment by johnlandonwood** [comment]
We will implement this by doing a count on a specific ISBN in the wishlist table

**Comment by johnlandonwood** [comment]
Not implementing due to time constraints
