### ISSUE TITLE
3.3 - As a borrower, I want to be able to view the book's condition on the checkout page

### ISSUE THREAD

**Issue by jheckSMU** [Djaenk/Textbook-Foundation#20]
2

As a borrower
I want to be able to view the book's condition on the checkout page
So that I know that the book I'm checking out is in usable condition

Given a borrower is on the checkout page
When they have a book selected
Then the book condition, cover image, book rating should be shown

**Comment by KirkWThomas** [comment]
book page is also checkout page, condition is shown.
