### ISSUE TITLE
4.2 - As a borrower I want to be able to see the scored book ratings below each book (see epic 10 for book ratings) so I can see how other people rated the book before checking it out

### ISSUE THREAD

**Issue by K3ll3nL** [Djaenk/Textbook-Foundation#24]
Given a borrower wants to view the book condiotn when they click on the book they will see a score between 1-5, the average.
Fibonacci Rating - 2

**Comment by ChrisSWood** [comment]
Interpreting this as "display the condition rating on the description page".

Completed in commit 033f4f28e9e3327141733c11577c7b08bc7ca4c2 on 5/20.
