### ISSUE TITLE
8.1 As a borrower, I want to be able to rate the condition of the textbook via survey, so that I can inform other potential borrowers of the book's condition.

### ISSUE THREAD

**Issue by Cweil42** [Djaenk/Textbook-Foundation#4]
5

Given a borrower has checked out a book, when they click on the book under the donor's profile, they should be able to give a rating of the textbook's condition

**Comment by KirkWThomas** [comment]
not implemented. product team revised requirement. does not make sense to rate condition before or after borrowing.
