### ISSUE TITLE
3.4 - As a borrower, I want to be able to view important information about the donor on the checkout page

### ISSUE THREAD

**Issue by jheckSMU** [Djaenk/Textbook-Foundation#41]
2

As a borrower
I want to be able to view a confirmation message before I check out
So I can make sure I'm checking out the correct book

Given a borrower is ready to check out
When they click 'check out'
Then a confirmation message should pop up before the transaction occurs

**Comment by KirkWThomas** [comment]
book page is checkout page. donor information is shown.
