### ISSUE TITLE
3.5 - As a borrower, I want to be able to visit the book donor's profile page from the check out screen

### ISSUE THREAD

**Issue by jheckSMU** [Djaenk/Textbook-Foundation#44]
3

As a borrower
I want to be able to visit the book donor's profile page from the check out screen
So I can learn more about the donor before I check out

Given a borrower is on the checkout page
When they view donor info
Then a profile picture and a link to their profile page should be shown

Given a borrower is on the checkout page
When they click on the link to the donor's profile page
Then they should be redirected to the donor's profile page

**Comment by KirkWThomas** [comment]
book and checkout screen the same. link created between book and profile
