### ISSUE TITLE
3.6 - As a borrower, I want to be able to click a 'Go Back' button to go back to the table

### ISSUE THREAD

**Issue by jheckSMU** [Djaenk/Textbook-Foundation#46]
1

As a borrower
I want to be able to click a 'Go Back' button to go back to the table
So if I changed my mind about checking it out, I can return to the table

Given a borrower is on the checkout page
If/When they click a 'Go Back' button
Then they should return to the book table page

**Comment by ChrisSWood** [comment]
Completed in commit 9398d5df9e4e9eed161e70cc1319ea471f9c6a94 on 5/21.
