### ISSUE TITLE
3.1 - As a borrower, I want to be able to click on a book in the books table and be directed to a 'checkout book' page

### ISSUE THREAD

**Issue by jheckSMU** [Djaenk/Textbook-Foundation#7]
2

As a borrower
I want to be able to click on a book in the books table and be directed to a 'checkout book' page
So I can view details about the book before I check it out

Given a borrower is on the books table
When they click a specific book's 'Checkout' link
They should be taken to the the 'checkout book' page for that book

**Comment by KirkWThomas** [comment]
finished. home page goes to book page. checkout from book page.
