### ISSUE TITLE
8.2 As a borrower, I want to be able to see previous borrowers' ratings when checking out my textbook, "So that I know the condition of the book I am checking out and can choose which book to check out if there are multiple.

### ISSUE THREAD

**Issue by Cweil42** [Djaenk/Textbook-Foundation#9]
3

Given a borrower is looking for a book, when they click on the book under the donor's profile, they should be able to see the ratings of the textbook's condition

**Comment by KirkWThomas** [comment]
revised requirement. textbook foundation does not 'return' books. books are donated and claimed, never returned. user story no longer applicable.
